# Generated by Django 3.2.11 on 2024-03-19 11:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_fsvourite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fsvourite',
            new_name='Favourite',
        ),
    ]
